language: node_js
node_js:
- '6'
install:
- yarn install
script:
- yarn lint
- yarn build
- yarn test
- yarn test:bench
deploy:
  provider: npm
  skip_cleanup: true
  on:
    tags: true
  email: robot.grylls@temando.com
  api_key:
    secure: gKpjBhColhr9trutD+5JXyjuR8c4bDzBKcOLma8ZRLDzzCDKdkMym3dsuTB/d49JIL7fygoIwz49KxgVDvpXdqX5THAcS0IkuaTWIMO6ESoFVNvYYK0AQjfzYAoZNxtIaQXEY35JQVygMpiSKS5S+wHgKtNDIxNVFTmOCGcHDbVqHbO2vzozdhqv6RFnWugqVLUIA1NCpHAi8kwmZt+62Ccd9O43wnJDDqcZsurOkzQe/CWosIAgiOTC2NmK2W7C5LJltbTIy45LENU6iZqMa2rq9kgmDqcPL4vEUkvckjZ+UxyAoeEihc70+gQqsL0d6n4HJn7Wd1Uk1DZoYXXuHv1hilGZhgpSWNAS4KSFKhifWJVMm+I7XDx6GVViIiSsfmjNZD02osK/W574hBjI7WTY+XTKcQUhHcFMPx9I02F0kKr9sYm95+EOR5iM0fEHy70aD+c4JANtYdVbBnWmPEdRZk6hUomUxa4fq9kZnNljpKzCv3F8+ZB0YQZylhCXwZy/6am+YkXJhwX8ABQm/uzB2g5PUKljXakQ8BasfyaU2YhqAiq5yVlOIhMZPpzZ4vIyYhene5U6ekmLyKuokGLpQWuDTrCuZjgE0vasoIzwVGyf7JW7KElgRQ9wmU6xBffxgzEixsvqiIo/TE7uVcaZZOt6tZ2XD7N/BpjxlL4=
