language: node_js

node_js:
  - '6'

install:
  - yarn install

script:
  - yarn lint
  - yarn build
  - yarn test
  - yarn test:bench

deploy:
  provider: npm
  on:
    tags: true
  email: robot.grylls@temando.com
  api_key: glPgfntEMpcyfGQbaxjnVfsYuVsx4Pf3xzv6A/P6lIMbvP0UZffqViun4I7ZQ3nZoGxqenjo1dLiUt8V2TvEwkv4Ulpld+qwGNlWfQgNxnhcEhWmrc2aMclN7AHvfzj+WQ2onWjD8r4jSazZ1L6qkHWIVoklJ+JRnPywiU4bQetEIuZ0VIUQd22T0aDydO47KGHNnmN5YXFbqGHqpqjhGkxRlTmFmCWaGT6elc/7xC9TEaDcrcGfC+YioGj+4uRFzEXyd+WU+2PIyh2ALu9qB33V3N5Otdr2SIFFy0GmIL2WL3ObRH5T99Qv0QTe/fmDgI3+ile9k7roJXXLqSZLomePKXSMfKDy9DNJsExPuyDwQ/gI3WtcwR+7AJn2cVVkbibDbtitx9ASYI2galYk3Gg5QEoYEsEOI0SesHbJGOD8IKSl2aE38gbxAL8pCuQuev+3Eoj6mXND8GQXth1eXzYZ6PYCO5i6pB2pof+sO3wMFUbrUY5bqC68/cIErPmOA2KFHHOS3HpVYn2ijWyiJK5QACDMbQfWblC67bdBRFIrMfXkV/THJ3Fs3lO7aE0bT5/ugHpaD+ikqAkR42obvGAZUKIS9kbPb5e9k/9cXabNsKjJSWHdj9ae9e/gNIdaDtfQlR1tXMMqXCQpeWG4ADi0uuOeRErNJletYY/k0lw=
