language: node_js

node_js:
  - "6"

install:
  - yarn install

script:
  - yarn lint
  - yarn build
  - yarn test
  - yarn test:bench

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm run release
  on:
    tags: true
